# Generated by Django 5.1.3 on 2024-11-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticaModelos1', '0002_alter_asignaciondetarea_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_tareas', to='PracticaModelos1.proyecto'),
        ),
    ]
